.PHONY: clean All

All:
	@echo "----------Building project:[ hangman_improved - Debug ]----------"
	@cd "hangman_improved" && "$(MAKE)" -f  "hangman_improved.mk"
clean:
	@echo "----------Cleaning project:[ hangman_improved - Debug ]----------"
	@cd "hangman_improved" && "$(MAKE)" -f  "hangman_improved.mk" clean
